#ifndef AST_TYPES_H_
#define AST_TYPES_H_


typedef enum {
    AST_NODE_SEMICOLON,
    AST_NODE_CYCLE,
    AST_NODE_IF,
    AST_NODE_DECLARATION,
    AST_NODE_ASSIGNMENT,
    AST_NODE_ARGUMENT,
    AST_NODE_CALL,
    AST_NODE_PARAMETER,
    AST_NODE_FUNCTION,
    AST_NODE_RETURN,
    AST_NODE_IDENTIFIER,
    AST_NODE_NUMBER,
    AST_NODE_OP_ADD,
    AST_NODE_OP_SUB,
    AST_NODE_OP_MUL,
    AST_NODE_OP_DIV,
    AST_NODE_OP_POW,
    AST_NODE_OP_NEG
} AstNodeType;


#endif // AST_TYPES_H_