#ifndef STATUS_H_ 
#define STATUS_H_


typedef enum {
// Successful status
    STATUS_OK = 0,
// Tree Errors
    STATUS_TREE_ROOT_HAS_PARENT,
    STATUS_TREE_MISSING_PARENT,
    STATUS_TREE_PARENT_CHILD_MISMATCH,
    STATUS_TREE_INVALID_BRANCH_STRUCTURE,
// System Errors
    STATUS_SYSTEM_OUT_OF_MEMORY,
    STATUS_SYSTEM_CALL_ERROR,
// Command Line Argument Errors
    STATUS_CLI_UNKNOWN_OPTION,
// Syntax Errors
    STATUS_PARSER_INVALID_IDENTIFIER,
// I/O Errors
    STATUS_IO_INVALID_USER_INPUT,
    STATUS_IO_FILE_OPEN_ERROR,
    STATUS_IO_FILE_EMPTY,
    STATUS_IO_FILE_READ_ERROR,
    STATUS_IO_FILE_CLOSE_ERROR,

    STATUS_SYNTAX_ERROR
} OperationStatus;


#endif // STATUS_H_